import { Repository } from '@/types/github';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'awesome-project',
    description: 'A really awesome project built with React and TypeScript',
    language: 'TypeScript',
    stargazers_count: 245,
    forks_count: 42,
    updated_at: '2024-11-15T10:30:00Z',
    visibility: 'public',
  },
  {
    id: 2,
    name: 'machine-learning-pipeline',
    description: 'End-to-end ML pipeline for data processing and model training',
    language: 'Python',
    stargazers_count: 189,
    forks_count: 28,
    updated_at: '2024-11-10T14:20:00Z',
    visibility: 'public',
  },
  {
    id: 3,
    name: 'api-gateway',
    description: 'High-performance API gateway with rate limiting and authentication',
    language: 'Go',
    stargazers_count: 567,
    forks_count: 89,
    updated_at: '2024-11-08T09:15:00Z',
    visibility: 'public',
  },
  {
    id: 4,
    name: 'ui-component-library',
    description: 'Modern and accessible UI components for React applications',
    language: 'JavaScript',
    stargazers_count: 1234,
    forks_count: 156,
    updated_at: '2024-11-05T16:45:00Z',
    visibility: 'public',
  },
  {
    id: 5,
    name: 'docker-compose-templates',
    description: 'Collection of Docker Compose templates for various tech stacks',
    language: 'Shell',
    stargazers_count: 89,
    forks_count: 23,
    updated_at: '2024-10-28T11:30:00Z',
    visibility: 'public',
  },
  {
    id: 6,
    name: 'blockchain-explorer',
    description: 'Web3 blockchain explorer with real-time transaction tracking',
    language: 'TypeScript',
    stargazers_count: 432,
    forks_count: 67,
    updated_at: '2024-10-20T13:00:00Z',
    visibility: 'public',
  },
];
